server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 리액트 라우팅을 위해 모든 요청을 index.html로 보냄
        try_files $uri $uri/ /index.html;
    }
}